export const locationsData = {
  'KwaZulu-Natal': [
    'DannhauserekuPhakameni',
    'Bulwer',
    'Ballito',
    'Amahlongwa',
    'Balgowan',
    'Hluhluwe',
    'Dundee',
    'Bergville',
    'Babanango',
    'Hattingspruit',
    'Adams Mission',
    'Franklin',
    'Groutville',
    'Amandawe',
    'Boston',
    'Ingwavuma',
    'Glencoe',
    'Colenso',
    'Louwsburg',
    'Madadeni',
    'Amanzimtoti (eManzimtoti)',
    'Himeville',
    'Shakaskraal',
    'Anerley',
    'Hilton',
    'Mkuze',
    'Greytown',
    'Elandslaagte',
    'Mahlabatini',
    'Newcastle',
    'Assagay',
    'Stuartstown (Ixopo)',
    'Stanger (KwaDukuza)',
    'Bazley Beach',
    'Howick',
    'Mtubatuba',
    'Kranskop',
    'Estcourt',
    'Nongoma',
    'Mountain View (Osizweni)',
    "Botha's Hill",
    'Kokstad',
    'Salt Rock',
    'Dududu',
    'Merrivale',
    'Ubombo',
    'Pomeroy',
    'Ladysmith',
    'Paulpietersburg',
    'Charlestown',
    'Cato Ridge',
    'Umzimkulu',
    'Mandeni',
    'Gamalakhe',
    'Mooi River',
    'Jozini',
    'Wasbank',
    'Pongola',
    'Ngagane',
    'Chatsworth',
    'Underberg',
    'Maphumulo',
    'Harding',
    'New Hanover',
    'Mbazwana',
    'Nquthu',
    'Ulundi',
    'Emadlangeni',
    'Clermont',
    'Umhlali',
    'Hibberdene',
    'Pietermaritzburg',
    'Kosi Bay town (Manguzi)',
    'Vryheid',
    'Kingsley',
    'Durban',
    'Ifafa Beach',
    'Richmond',
    'Gillitts',
    'Izingolweni (eZinqoleni)',
    'Wartburg',
    'Hillcrest',
    'Izotsha',
    'Dalton',
    'Inanda',
    'Kelso',
    'Inchanga',
    'Leisure Bay',
    'Isipingo',
    'KwaCele',
    'Kingsburgh',
    'Manaba Beach',
    'Kloof',
    'Margate',
    'KwaMakhutha',
    'Marina Beach',
    'KwaMashu',
    'Melville',
    'La Mercy',
    'Umtalumi (Mthwalume)',
    'Mpumalanga',
    'Umzumbe',
    'New Germany',
    'Munster',
    'Ntuzuma',
    'Oshabeni (oShabeni)',
    'Tongaat (oThongathi)',
    'Palm Beach',
    'Pinetown',
    'Park Rynie',
    'Phoenix',
    'Pennington',
    'Prospecton',
    'Port Edward',
    'Queensburgh',
    'Port Shepstone',
    'Shallcross',
    'Ramsgate',
    'Umbumbulu',
    'Scottburgh',
    'Umdloti (eMdloti)',
    'Sea Park',
    'Umgababa',
    'Sezela',
    'Umhlanga (uMhlanga)',
    'Shelly Beach',
    'Umkomaas (eMkhomazi)',
    'Southbroom',
    'Umlazi',
    'Southport',
    'Verulam',
    'Sunwich Port',
    'Waterfall',
    'Trafalgar',
    'Westville',
    'Umtentweni (eMthenteni)',
    'Umzinto',
    'Uvongo',
    'Weza',
  ],
  'Western Cape': [
    'Atlantis',
    'Milnerton',
    'Aurora',
    'Ashton',
    'Arniston',
    'Avontuur',
    'Montagu',
    'Beaufort West',
    'Bellville',
    "Mitchell's Plain",
    'Bitterfontein',
    'Bonnievale',
    'Baardskeerdersbos',
    'Albertinia',
    'Barrydale',
    'Laingsburg',
    'Blouberg',
    'Muizenberg',
    'Chatsworth',
    'Ceres',
    "Betty's Bay",
    'Amaliënstein',
    'Ladismith',
    'Leeu-Gamka',
    'Blue Downs',
    'Noordhoek',
    'Citrusdal',
    'De Doorns',
    'Birkenhead',
    'Bergplaas',
    'Calitzdorp',
    'Matjiesfontein',
    'Bothasig',
    'Nyanga',
    'Clanwilliam',
    'De Hollandsche Molen',
    'Botrivier',
    'Boggomsbaai',
    'Oudtshoorn',
    'Merweville',
    'Brackenfell',
    'Parow',
    'Darling',
    'Denneburg',
    'Bredasdorp',
    'Bracken Hill',
    'De Rust',
    'Murraysburg',
    'Cape Town',
    'Philadelphia',
    'Doringbaai',
    'Franschhoek',
    'Caledon',
    'Brandwag',
    'Nelspoort',
    'Crossroads',
    "Simon's Town",
    'Dwarskersbos',
    'Gouda',
    'Dennehof',
    'Brenton-on-Sea',
    'Prince Albert',
    'Delft',
    'Somerset West',
    'Ebenhaeser',
    'Kayamandi',
    'Elgin',
    'Eerste River',
    'Elands Bay',
    'Klapmuts',
    'Elim',
    'Dana Baai',
    "Elsie's River",
    'Goedverwacht',
    'Languedoc',
    'Fisherhaven',
    'De Hoop',
    'Fish Hoek',
    'Graafwater',
    'McGregor',
    'Franskraalstrand',
    'De Vlugt',
    'Goodwood',
    'Grotto Bay',
    'Gansbaai',
    'Dysselsdorp',
    "Gordon's Bay",
    'Hopefield',
    'Op-die-Berg',
    'Genadendal',
    'Farleigh',
    'Guguletu',
    'Jacobsbaai',
    'Paarl',
    'Grabouw',
    'Friemersheim',
    'Hout Bay',
    'Jakkalsfontein',
    'Pniel',
    'Greyton',
    'George',
    'Khayelitsha',
    'Kalbaskraal',
    'Prince Alfred Hamlet',
    'Hawston',
    'Glentana',
    'Kraaifontein',
    'Klawer',
    'Rawsonville',
    'Hermanus',
    'Gouna',
    'Kuils River',
    'Koekenaap',
    'Robertson',
    'Hotagterklip',
    'Gouritsmond',
    'Langa',
    'Koringberg',
    'Robertsvlei',
    'Infanta',
    'Great Brak River',
    'Macassar',
    "Lamber's Bay",
    'Rozendal',
    'Kleinbaai',
    'Groot-Jongensfontein',
    'Melkbosstrand',
    'Langebaan',
    'Saron',
    'Kleinmond',
    'Haarlem',
    'Mfuleni',
    'Langebaanweg',
    'Stellenbosch',
    'Klipdale',
    'Hartenbos',
    'Moorreesburg',
    'Tulbagh',
    "L'Agulhas",
    'Heidelberg',
    'Paternoster',
    'Wellington',
    'Onrusrivier',
    'Herbertsdale',
    'Piketberg',
    'Wolseley',
    'Papiesvlei',
    'Herold',
    'Porterville',
    'Worcester',
    'Pearly Beach',
    'Hoekwil',
    'Redelinghuys',
    'Riviersonderend',
    'Jonkersberg',
    'Riebeek-Kasteel',
    'Rooi Els',
    'Karatara',
    'Riebeek West',
    'Sandbaai',
    'Keurboomsrivier',
    'Saldanha',
    'Skipskop',
    'Keurboomstrand',
    'St Helena Bay',
    'Stanford',
    'Knysna',
    'Strandfontein',
    'Struisbaai',
    'Kranshoek',
    'Vanrhynsdorp',
    'Suiderstrand',
    'Kurland Estate',
    'Velddrif',
    'Suurbraak',
    'Little Brak River',
    'Vredenburg',
    'Swellendam',
    'Matjiesrivier',
    'Vredendal',
    'Uilenkraalsmond',
    'Mossel Bay',
    'Wupperthal',
    'Van Dyksbaai',
    "Nature's Valley",
    'Yzerfontein',
    'Vermont',
    'Noetzie',
    'Villiersdorp',
    'Pacaltsdorp',
    'Wolvengat',
    'Plettenberg Bay',
    'Port Beaufort',
    'Puntjie',
    'Rheenendal',
    'Riversdale',
    'Ruiterbos',
    'Schoemanshoek',
    'Sedgefield',
    'Slangrivier',
    'Stilbaai',
    'Touwsranten',
    'Twee Rivieren',
    'Uniondale',
    'Vanwyksdorp',
    'Vermaaklikheid',
    'Volmoed',
    'Victoria Bay',
    'Vleesbaai',
    'Wilderness',
    'Wittedrift',
    'Witsand',
    'Woodville',
    'Zoar',
  ],
  Gauteng: [
    'Alexandra',
    'Alberton',
    'Atteridgeville',
    'Boipatong',
    'Meyerton',
    'Devon',
    'Carletonville',
    'Hekpoort',
    'Bhongweni',
    'Bekkersdal',
    'Diepsloot',
    'Bedfordview',
    'Bronberg',
    'Bophelong',
    'Randvaal',
    'Heidelberg',
    'Khutsong',
    'Kagiso',
    'Brandvlei',
    'Westonaria',
    'Ennerdale',
    'Benoni',
    'Bronkhorstspruit',
    'Evaton',
    'Walkerville',
    'Impumelelo',
    'Fochville',
    'Kromdraai',
    'Mohlakeng',
    'Simunye, Westonaria',
    'Johannesburg',
    'Boksburg',
    'Centurion',
    'Sebokeng',
    'Ratanda',
    'Kokosi',
    'Krugersdorp',
    'Panvlak Gold Mine',
    'Borwa, Westonaria',
    'Lenz (Lenasia)',
    'Brakpan',
    'Cullinan',
    'Sharpeville',
    'Greenspark',
    'Magaliesburg',
    'Randfontein',
    'Modderfontein',
    'Bapsfontein',
    'Ekangala',
    'Vanderbijlpark',
    'Wedela',
    'Muldersdrift',
    'Toekomsrus',
    'Orange Farm',
    'Clayville',
    'Ga-Rankuwa',
    'Vereeniging',
    'Welverdiend',
    'Munsieville',
    'Zenzele',
    'Randburg',
    'Daveyton',
    'Hammanskraal',
    'Blybank',
    'Rietvallei',
    'Roodepoort',
    'Duduza',
    'Irene',
    'Silverfields',
    'Sandton',
    'Edenvale',
    'Mabopane',
    'Tarlton',
    'Soweto',
    'Holfontein',
    'Mamelodi',
    'Germiston',
    'Pretoria',
    'Isando',
    'Rayton',
    'Katlehong',
    'Refilwe',
    'Kempton Park',
    'Soshanguve',
    'KwaThema',
    'Winterveld',
    'Dunnottar',
    'Zithobeni',
    'Nigel',
    'Reiger Park',
    'Springs',
    'Tembisa',
    'Tokoza',
    'Tsakane',
    'Vosloorus',
    'Wattville',
    'Luweero',
  ],
  Mpumalanga: [
    'Barberton',
    'Belfast',
    'Bethal',
    'Breyten',
    'Bushbuckridge',
    'Carolina',
    'Delmas',
    'Dullstroom',
    'Eerstehoek',
    'Elukwatini',
    'Emalahleni (Witbank)',
    'Ermelo',
    'Graskop',
    'Hazyview',
    'Hendrina',
    'Komatipoort',
    'Kriel',
    'Lydenburg',
    'Machadodorp',
    'Malelane',
    'Middleburg',
    'Nelspruit (Mbombela)',
    'Ohrigstad',
    'Piet Retief',
    'Pilgrim\'s Rest',
    'Sabie',
    'Secunda',
    'Standerton',
    'Thulamahashe',
    'Volksrust',
    'Wakkerstroom',
    'White River',
  ],
  Limpopo: [
    'Alldays',
    'Bela-Bela (Warmbaths)',
    'Burgersfort',
    'Dendron',
    'Duiwelskloof (Modjadjiskloof)',
    'Ellisras (Lephalale)',
    'Giyani',
    'Groblersdal',
    'Hoedspruit',
    'Jane Furse',
    'Lebowakgomo',
    'Lephalale',
    'Louis Trichardt (Makhado)',
    'Marble Hall',
    'Messina (Musina)',
    'Modimolle (Nylstroom)',
    'Mokopane (Potgietersrus)',
    'Mookgophong',
    'Musina',
    'Phalaborwa',
    'Polokwane (Pietersburg)',
    'Seshego',
    'Thabazimbi',
    'Thohoyandou',
    'Tlakgameng',
    'Tzaneen',
    'Vaalwater',
    'Vivo',
    'Warmbaths',
  ],
  'North West': [
    'Bloemhof',
    'Brits',
    'Christiana',
    'Coligny',
    'Delareyville',
    'Ga-Rankuwa',
    'Ganyesa',
    'Groot Marico',
    'Hartbeesfontein',
    'Koster',
    'Klerksdorp',
    'Lichtenburg',
    'Mafikeng (Mmabatho)',
    'Mahikeng',
    'Makwassie',
    'Mooinooi',
    'Orkney',
    'Ottosdal',
    'Parys',
    'Potchefstroom',
    'Rustenburg',
    'Schweizer-Reneke',
    'Stilfontein',
    'Sun City',
    'Taung',
    'Ventersdorp',
    'Vryburg',
    'Wolmaransstad',
    'Zeerust',
  ],
  'Free State': [
    'Bethlehem',
    'Bloemfontein',
    'Botshabelo',
    'Bothaville',
    'Brandfort',
    'Clarens',
    'Clocolan',
    'Dealesville',
    'Deneysville',
    'Ficksburg',
    'Fouriesburg',
    'Frankfort',
    'Harrismith',
    'Heilbron',
    'Hennenman',
    'Hoopstad',
    'Koffiefontein',
    'Kroonstad',
    'Ladybrand',
    'Lindley',
    'Marquard',
    'Odendaalsrus',
    'Oranjeville',
    'Parys',
    'Phuthaditjhaba',
    'Reitz',
    'Rosendal',
    'Sasolburg',
    'Senekal',
    'Smithfield',
    'Thaba Nchu',
    'Theunissen',
    'Trompsburg',
    'Viljoenskroon',
    'Virginia',
    'Vrede',
    'Vredefort',
    'Welkom',
    'Wesselsbron',
    'Winburg',
  ],
  'Eastern Cape': [
    'Adelaide',
    'Addo',
    'Albany',
    'Alexandria',
    'Aliwal North',
    'Bathurst',
    'Bedford',
    'Berlin',
    'Bisho',
    'Butterworth',
    'Cathcart',
    'Cintsa',
    'Cradock',
    'Despatch',
    'Dutywa',
    'East London',
    'Elliot',
    'Fort Beaufort',
    'Gonubie',
    'Graaff-Reinet',
    'Grahamstown (Makhanda)',
    'Hamburg',
    'Hankey',
    'Hofmeyr',
    'Humansdorp',
    'Jeffreys Bay',
    'Joubertina',
    'Kareedouw',
    'King William\'s Town',
    'Kirkwood',
    'Komga',
    'Kenton-on-Sea',
    'Lady Frere',
    'Lady Grey',
    'Libode',
    'Lusikisiki',
    'Maclear',
    'Makhanda (Grahamstown)',
    'Mdantsane',
    'Middelburg',
    'Mthatha (Umtata)',
    'Ngcobo',
    'Noupoort',
    'Oyster Bay',
    'Paterson',
    'Patensie',
    'Port Alfred',
    'Port Elizabeth (Gqeberha)',
    'Port St Johns',
    'Queenstown',
    'Rhodes',
    'Somerset East',
    'St Francis Bay',
    'Steynsburg',
    'Steytlerville',
    'Stutterheim',
    'Tarkastad',
    'Tsolo',
    'Uitenhage',
    'Whittlesea',
    'Willowmore',
  ],
  'Northern Cape': [
    'Alexander Bay',
    'Barkly West',
    'Britstown',
    'Calvinia',
    'Campbell',
    'Carnarvon',
    'Colesberg',
    'Danielskuil',
    'De Aar',
    'Douglas',
    'Griekwastad',
    'Groblershoop',
    'Hanover',
    'Hopetown',
    'Hotazel',
    'Kakamas',
    'Kathu',
    'Keimoes',
    'Kenhardt',
    'Kimberley',
    'Kuruman',
    'Lime Acres',
    'Marydale',
    'Orania',
    'Pofadder',
    'Port Nolloth',
    'Postmasburg',
    'Prieska',
    'Richmond',
    'Springbok',
    'Strydenburg',
    'Sutherland',
    'Upington',
    'Victoria West',
    'Vryburg',
    'Warrenton',
    'Williston',
  ],
};
