/**
 * Sync SEO Keywords from Database to Frontend
 * 
 * This script exports all keyword slugs from the database
 * and generates a TypeScript file for the frontend.
 * 
 * Run: npx ts-node scripts/sync-keywords-to-frontend.ts
 */

import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';

const prisma = new PrismaClient();

async function syncKeywordsToFrontend() {
    console.log('🔄 Syncing keywords from database to frontend...\n');

    try {
        // Fetch all keywords from database
        const keywords = await prisma.seoKeyword.findMany({
            select: {
                slug: true,
                keyword: true,
                category: true,
                priority: true,
            },
            orderBy: [
                { priority: 'asc' },
                { category: 'asc' },
                { keyword: 'asc' },
            ],
        });

        console.log(`📊 Found ${keywords.length} keywords in database\n`);

        // Group by category for better organization
        const byCategory: Record<string, string[]> = {};
        keywords.forEach(kw => {
            if (!byCategory[kw.category]) {
                byCategory[kw.category] = [];
            }
            byCategory[kw.category].push(kw.slug);
        });

        // Generate TypeScript content
        const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * Generated by: npx ts-node scripts/sync-keywords-to-frontend.ts
 * Generated at: ${new Date().toISOString()}
 * Source: Database seo_keywords table
 * 
 * Total keywords: ${keywords.length}
 */

// All valid SEO keyword slugs from database
export const SEO_KEYWORD_SLUGS: string[] = [
${keywords.map(kw => `  '${kw.slug}',`).join('\n')}
];

// Keywords grouped by category
export const KEYWORDS_BY_CATEGORY: Record<string, string[]> = {
${Object.entries(byCategory).map(([cat, slugs]) =>
            `  ${cat}: [\n${slugs.map(s => `    '${s}',`).join('\n')}\n  ],`
        ).join('\n')}
};

// Quick lookup set for validation
export const SEO_KEYWORDS_SET = new Set(SEO_KEYWORD_SLUGS);

// Validate if a keyword slug is valid
export function isValidKeyword(slug: string): boolean {
  return SEO_KEYWORDS_SET.has(slug);
}

// Get all keywords (for backward compatibility)
export const SEO_KEYWORDS = SEO_KEYWORD_SLUGS;

// Statistics
export const KEYWORD_STATS = {
  total: ${keywords.length},
  byCategory: {
${Object.entries(byCategory).map(([cat, slugs]) =>
            `    ${cat}: ${slugs.length},`
        ).join('\n')}
  },
  generatedAt: '${new Date().toISOString()}',
};
`;

        // Write to frontend lib directory
        const frontendPath = path.join(__dirname, '../../frontend/src/lib/seo-keywords.generated.ts');
        fs.writeFileSync(frontendPath, content, 'utf-8');

        console.log(`✅ Generated: ${frontendPath}`);
        console.log(`\n📊 Keywords by category:`);
        Object.entries(byCategory).forEach(([cat, slugs]) => {
            console.log(`   ${cat}: ${slugs.length}`);
        });

        console.log('\n📝 Next step: Update seo-generation.ts to import from seo-keywords.generated.ts');
        console.log('   Add: import { SEO_KEYWORDS } from \'./seo-keywords.generated\';');

    } catch (error) {
        console.error('❌ Error syncing keywords:', error);
        throw error;
    } finally {
        await prisma.$disconnect();
    }
}

syncKeywordsToFrontend()
    .then(() => {
        console.log('\n✅ Sync completed successfully!');
        process.exit(0);
    })
    .catch((error) => {
        console.error('❌ Sync failed:', error);
        process.exit(1);
    });
